baseurl = "https://elsaetantoine.com/"
metaDataFormat = "yaml"
title = "E & A"
theme = "blist-hugo-theme"
enableEmoji = true

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    contentDir = "content/" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Elsa & Antoine"
      introSubtitle = "23 septembre 2023 üíç"
      introPhoto = "/picture.jpg"

    [[languages.en.menu.main]]
        name = "Notre histoire"
        url = "/histoire/"
        weight = 1

    [[languages.en.menu.main]]
        name = "Programme"
        url = "/programme/"
        weight = 2
        
    [[languages.en.menu.main]]
        name = "Lieu"
        url = "/lieu/"
        weight = 3
        
    [[languages.en.menu.main]]
        name = "H√©bergement"
        url = "/hebergement/"
        weight = 4
        
    [[languages.en.menu.main]]
        name = "T√©moins"
        url = "/temoins/"
        weight = 5
        
    [[languages.en.menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 6
        

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = false

  # Custom copyright - optional
  copyright = "¬© Elsa ‚ù§Ô∏è Antoine"
  favicon = "/favicon.ico"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"
  
# The page bundle that is shown on the front page
frontBundle = "blog"

# [params.homepage.social]
#   # Global params common for both languages
#   title = "Confirmer ma pr√©sence"
#   description = "23 ao√ªt 2023, Ch√¢teau Bayard"
#   twitter = "https://twitter.com/"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

googleAnalytics = 'G-248HJC8VNE'